# Generated by Django 4.1.3 on 2022-11-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Parent_or_Guardian', models.CharField(max_length=40)),
                ('Issue', models.CharField(choices=[('Fever', 'Cold/Cough/Fever'), ('migraine', 'Migraine'), ('sugar', 'Sugar/Blood pressure'), ('skin', 'Rashes/skin issues'), ('digestion', 'Digestion Issues'), ('others', 'Other issue')], default='Fever', max_length=50)),
                ('Detailed_Reason', models.TextField(max_length=500)),
                ('suffering_from', models.DateField(auto_now_add=True)),
                ('Gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others'), ('not', 'Not like to disclose')], max_length=50)),
                ('Age', models.IntegerField()),
                ('Blood_group', models.CharField(max_length=10)),
                ('Availability_slot', models.CharField(choices=[('mrg10', 'Mrg 10-11'), ('mrg11', 'Mrg 11-12'), ('aft12', 'Aft 12-01')], default='mrg10', max_length=30)),
                ('checkup_on', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
